### PR TITLE
Make Spain an actual democracy

### PR DESCRIPTION
**Pull request by txus**
This is a fix for (or at least an attempt to fix) bug number 1-O (which is [demonstrated in videos here](http://spanishpolice.github.io)), originally reported on the 1st October 2017 [by the BBC](https://www.bbc.com/news/world-europe-41461032). The issue was that 10.000 police were sent to brutally repress a peaceful vote in Catalonia.

Originally it was patched by sentencing elected democrats, responsible for the vote, to a combined 100 years in prison, but as it turns out, that didn't really fix the underlying issue.

It seems that the problem surfaced again this month as a regression, reported by the BBC [here](https://www.bbc.com/news/world-europe-49974289). Here are some [videos demonstrating the latest regression](http://catalanrepression.github.io) (October 2019).

### Tests

✅ International media outlets (passing)
✅ Renowned scholars and law experts (passing)
✅ Human rights & pro-democracy watchdogs (passing)
✅ Hong Kong pro-democracy activists (passing)
❌ Spanish State media (failing*)

*I couldn't make this last one pass because for some reason it always reports the opposite of what the rest of the tests report. Might be a flaky test, so it might be okay to ignore it.

### CODE REVIEW

**Comment by josepjaume** [comment]
Thanks for your contribution! I've also been trying to (unsuccessfully) fix this for a long time. Can I suggest adding this to the Spanish State media test cases?

https://catalanrepression.github.io/
https://spanishpolice.github.io/

**Comment by hid7456** [comment]
This repository cannot be fixed and I expect this to be closed.

The current maintainer seems to be more interested in beating collaborators and arms trafficking than this repository. I suppose moving around weapons to hurt people runs in the family.

The previous maintainer wasn't much better, he certainly preferred to go around with as many women as he could, and his pastime were shooting endangered species with the money of the repository collaborators. When collaborators started proposing PR he didn't like, he staged a coup d'etat to make him look like the good guy and keep repository as he wanted.

And the previous one... don't make me talk about him. Hundreds of thousands of deaths, summary executions, negotiations with other fascists maintainers to unite repositories.
I know the maintainer's private life shouldn't affect the software, but I'd feel very dirty to use a software that has such a lowlife maintainer.

One would expect that after 80 years they would have switched to Agile, but they're still stuck with the old "hit the collaborator until shuts up or dies".

My suggestion is starting anew modularizing it. Separate it in pieces of code which are not rotten yet and write tests for them. Later (10 thousand years seems a prudent amount of time) reintegrate them if the code no longer has fascist smell.

p.s. beware of the organization this repository belongs too, it's full of hypocrites. They won't shut up when other maintainers consistently hit with police bats their collaborators but won't even blink when this is done by a member of their organization.

p.s.2 This is obviously an anonymous account. You never know when the Spanish Inquisition is about to knock at your door...

**Comment by hacknug** [comment]
LGTM 👍

**Comment by commonsense59** [comment]
It is interesting how the idea of a cited city blind the people. 

1. Spain is a democracy; otherwise you won't be able to:

   1. Vote for your government (local or national).
   2. Make the linguistic inversion you are doing in Catalonia imposing a local language.
   3. A local authority who promotes and supports any dissidence will go in jail or disappear.
   4. Any parliament who oppose to the main authority of the government will be dissolved (specially if they vote an illegal law who compromises the territorial integrity, with public money)
   5. The police will receive the order to attack instead of just stand there waiting for flying rocks (ass all the world has seen most of them has done).

2. The most democratic countries in the world has:

   1. Forbidden nationalist or fragmentary movements in any sense.
   2. Condemn the attempt to divide the country, with more severe laws for public authorities.
   3. The police control the public order, specially if a mass of fanatic people are destroying a city, burning cars, and applying vandalism to the property... that's actually the police's work.

3) In totalitarian governments (and religion) there are characteristics more similar to the Catalan government actually:

   1. The leather exaltation. (Maduro, Peron, Franco, Puigdemont)
   2. Creation of a foreign enemy to hate. (EEUU, URSS, Spain)
   3. Promotion of a moral superiority feeling in the people (the harder workers, the most pacific, the most honest, the smartest).
   4. Manipulation of the history to exalt the national feeling (Institut Nova Història)
   5. Promise of a better idyllic future (Comunism, Republic, Revolution, Freedom)
   6. Control of the education to promote the government intentions (Komsomol, Hitlerjugend)
   7. Control of the media and publicity campaign.
   8. Immunity for the authority and impose the supposed interest of the people over the rights state. (this is a perfect formula to create a dictature)

All this is in any Social Engineering book or tutorial of psychology of masses. And the mass now don't understand they were lied and manipulated since 1990.

Catalan politicians created all this movement promised the sky and then they said clearly the were bluffing. But when things go bad  there is not problem because they already have a foreign enemy to blame.

Spain is a fail country, not for the supposed repression , but for not stopping all this on time:

   1. Keep the control of the education competences.
   2. Keep Pujol in the head of Catalonia for 21 years. (Keep the corrupts of one side to protect the ones in the other side this produced al teat a 3% of errors)
   3. Not forbid the linguistic inversion (this is a special one because psychologically the language creates most of the division between human groups, as a different language speaker is not recognized as part of the same group in the subcontinent) 
   4. Not suspend the Catalan Parlament when they created the disconnection laws.
   5. Not apply correctly (or in time) the article 155.
   6. Not supervise the educations in the schools (which some of them don't even accomplish the 25% of Spanish classes)
   7. Keep the linguistic filter laws that favors the existence of only Catalans in public positions in Catalonia.

**Comment by ibonkonesa** [comment]
LOL

**Comment by txus** [comment]
You must agree with me in that creating a Github user just to post this is a little bit sad @commonsense59.

**Comment by xerpi** [comment]
Looks good to me,

Reviewed-by: Sergi Granell <xerpi.g.12 at gmail.com>

**Comment by tuxillo** [comment]
I wholeheartedly disagree with the core message of this PR because is deceitful and dishonest in my opinion.
Otherwise I support free speech be it in "comedy" or any other communication method. I also think that Github is not the place for this kind of discussion when there are much more appropriate platforms out there.

**Comment by txus** [comment]
> I wholeheartedly disagree with the core message of this PR because is deceitful and dishonest in my opinion.
> Otherwise I support free speech be it in "comedy" or any other communication method. I also think that Github is not the place for this kind of discussion when there are much more appropriate platforms out there.

I wouldn't have used Github if it wasn't for the censorship they've agreed to do in the name of fascism. Thanks to Github, people who are in Spain cannot visit a website about a grass-roots democratic movement that has hurt nobody.

**Comment by josepjaume** [comment]
That platform is called a parliament, @tuxillo. Discussion would be happening there if our leaders weren't jailed precisely for having it.

Damn, Carme Forcadell is going to spend a decade in prison just for allowing the debate!

**Comment by tuxillo** [comment]
If you happen to open a reddit (or any other forum) thread, please post the link and the conversation can be continued there. This is no place. Thanks.

**Comment by hacknug** [comment]
This is just as good as any other place as long as the convo stays respectful. Repo owners can close or lock discussion if they feel like it.

Anyone feels like sharing this on HN?

**Comment by edgarriba** [comment]
is this repo using tests for pushing/deciding stuff ?
what's the governance policy here ?

github losing transparency

**Comment by andoniabedul** [comment]
This is disgusting, now Github is intruded on political issues and is totally disgusting. Why Github don't post the takedowns on Iran or Crimea accounts, for example? Why some takedowns are being published and others not?

**Comment by edgarriba** [comment]
@andoniabedul new microsoft policy ?

**Comment by danielmana** [comment]
tsunami

**Comment by hamddan4** [comment]
> If you happen to open a reddit (or any other forum) thread, please post the link and the conversation can be continued there. This is no place. Thanks.

Discussion thread on reddit: https://www.reddit.com/r/worldnews/comments/dp4quv/spain_has_become_the_3rd_country_after_china_and/

**Comment by Tonetete** [comment]
> You must agree with me in that creating a Github user just to post this is a little bit sad @commonsense59.

What is really sad is your fix is not passing the pipeline since.... No matter which year you're reading this.

**Comment by Tonetete** [comment]
> The existence of "[El Valle de los Caidos](https://en.wikipedia.org/wiki/Valle_de_los_Ca%C3%ADdos)", a place which served as a burial ground and place of devotion of the fascist dictator Franco from 1975 until its exhumation a week ago - that seemed to be more of a tribute to fascism than an exhumation - shows that this repository has a worrying amount of technical debt that hasn't been appropriately addressed for decades.

Please you managers need to reach an agreement with the stakeholders and stop changing the specs on the process. Franco is already exhumated and this has been patched, create another ticket for this "tribute thing" but probably no one will review this, there are many tickets way more important in backlog such as "improve the economy", "improve social security", "improve education" and many many others. Stop changing priorities!

**Comment by KevinBlandy** [comment]
吵吵啥这？

**Comment by josepjaume** [comment]
Has anyone here tried microservices? Thinking about that or a monorepo approach, but I don't think the monolith is going to hold much longer.

**Comment by naoisegolden** [comment]
Seems that the original maintainers are unresponsive.

**Comment by BielStela** [comment]
Uops browser hanged when clicking Approve :(

**Comment by waiting-for-dev** [comment]
I guess we should fork the repo and maintain it ourselves...

**Comment by pacofdeznra** [comment]
@mlinksva @jessephus can you merge it please?

**Comment by elena20ruiz** [comment]
@faix please, could you do something with this PR?

**Comment by pauroger** [comment]
LGTM

**Comment by thecyberd3m0n** [comment]
I think with M$ Github more test will start to fail after their policies upgrades. Next step will be ditching tests, and censoring people who contest the policies.

In free time, I'll move my stuff to Gitlab. Just like I moved from Windows to Linux, from Skype to Signal and from Github to Gitlab

**Comment by thecyberd3m0n** [comment]
https://github.com/thecyberd3m0n/boycott-github-and-ms/blob/master/README.md

Please consider following my boycott. Move to other platform, they're better anyway.

**Comment by hacknug** [comment]
@thecyberd3m0n you might wanna reconsider:
- https://www.theregister.co.uk/2019/10/16/gitlab_employees_gagged/
- https://www.theregister.co.uk/2019/11/04/gitlab_chinese_russian_support_staff_ban/

**Comment by rekols** [comment]
Support you, support Spain

**Comment by lee-dohm** [comment]
As we had stated the [previous version](https://github.com/github/gov-takedowns/tree/1eadc7c478b22addb8c7969eda9e49c5090faa77#contributing) of the README in this repo

> We do not accept Pull Requests in this repository.

To clarify and explain why, we made some [clarifications](https://github.com/github/gov-takedowns/blob/master/README.md), including

> We publicly post those notices, unchanged (other than redactions of personal information), because we are concerned about Internet censorship

and that

> We do not accept Pull Requests in this repository because the notices we post are verbatim from the notifying government.

For these reasons, we are closing this pull request. If you have further questions, please feel free to contact [GitHub Support](https://support.github.com/contact).

**Pull request closed without merging**
