### PR TITLE
Update 2019-10-23-GuardiaCivil.md

### PR DESCRIPTION
**Pull request by fewrare**
Ã± changed by ñ.

### CODE REVIEW

**Comment by jiwidi** [comment]
@txus 

Please do not include your political opinions on this document, regardless of your considerations whether this is terrorism or not the file `2019-10-23-GuardiaCivil.md` must only include the official notice Spain government gave Github in order to take down the repository. We should keep transparency on those files and not include our political opinions.

**Comment by txus** [comment]
> @txus
> 
> Please do not include your political opinions on this document, regardless of your considerations whether this is terrorism or not the file `2019-10-23-GuardiaCivil.md` must only include the official notice Spain government gave Github in order to take down the repository. We should keep transparency on those files and not include our political opinions.

What part of "censoring a democratic organization as terrorism who's protesting for the fact that elected congress representatives are in jail for organizing a vote" is outside of politics exactly?

**Comment by jiwidi** [comment]
> > @txus
> > Please do not include your political opinions on this document, regardless of your considerations whether this is terrorism or not the file `2019-10-23-GuardiaCivil.md` must only include the official notice Spain government gave Github in order to take down the repository. We should keep transparency on those files and not include our political opinions.
> 
> What part of "censoring a democratic organization as terrorism who's protesting for the fact that elected congress representatives are in jail for organizing a vote" is outside of politics exactly?

I dont think you understand that `2019-10-23-GuardiaCivil.md` is the official notice given by the Spanish state to github asking to close the repository access. You may agree with it or not but we can't change the words on it, if we were to do so we will be in fact breaking the transparency this repository is meant to provide.

The aim of this repository is to provide transparency to the cases where a repository is taken down and not to write down your own political speech. This is how this repository works:

1. Github receives an official notice from a state asking to close down certain repository access within that state.

2. Github follows the obeys the law and proceeds to do so.

3. Github publishes the received notice on this repository to provide transparency to his users on why they can't access this repository anymore.


In no moment GitHub takes any political side, neither the state or the repository owner. Github just followed the law and took the gratitude of providing its users with why the repository was closed.

Don't make this repository a personal weapon to your political speech, please

**Comment by vitelone** [comment]
> In no moment GitHub takes any political side, neither the state or the repository owner.

Saying "we are only following orders" when censoring might be amoral --it is indeed political all the same.

**Comment by Woundorf** [comment]
@jiwidi Note that "obeying a government or police force" and "following the law" are different things.

**Comment by tunnckoCore** [comment]
What tha fack are you all talking about?! @fewrare is just changing a single letter here. Please proceed without taking a side and talking about political preferences.

**Comment by JuanjoSalvador** [comment]
Leaving behind the comments and political fightings, this PR could be merged without any problem. And the other ones that are suggesting the full or partial replacement of the original text, just because they disagree with an official comunicate, should be inmediately closed.

GitHub transparency repository is not your propaganda.

**Comment by ctubio** [comment]
GitHub transparency repository is not a free grammar checker service for failed states.

**Comment by rekols** [comment]
hhh

**Pull request closed without merging**
