### PR TITLE
Dear Github, you're being played by a failed state

### PR DESCRIPTION
**Pull request by thomasmaas**

### CODE REVIEW

**Comment by tunnckoCore** [comment]
Close. This repository is nothing to do with politics or taking a side. It's for transparency of @GitHub as an organization. Putting all the communication sent to them by other parties - that's transparency.

**Comment by drpicox** [comment]
What is doing GitHub is great!
It is really nice to see a company doing real transparency.

But I do not understand your comment @tunnckoCore , ¿did you have read the README?

https://github.com/github/gov-takedowns#contributing

> **Contributing**
> We do not accept Pull Requests in this repository. _Feel free to comment or make suggestions_, 
> but note that we do not actively monitor contributions to this repository. 
> If you would like to contact GitHub about this repository, please contact GitHub Support.

GitHub is just embracing free of speech. That is wonderful!

**Comment by tunnckoCore** [comment]
> ¿did you have read the README?

Yes, I did. And as you quoted. It's nonsense to contribute such "changes". Such PRs are obviously out of scope.

**Comment by lee-dohm** [comment]
As we had stated the [previous version](https://github.com/github/gov-takedowns/tree/1eadc7c478b22addb8c7969eda9e49c5090faa77#contributing) of the README in this repo

> We do not accept Pull Requests in this repository.

To clarify and explain why, we made some [clarifications](https://github.com/github/gov-takedowns/blob/master/README.md), including

> We publicly post those notices, unchanged (other than redactions of personal information), because we are concerned about Internet censorship

and that

> We do not accept Pull Requests in this repository because the notices we post are verbatim from the notifying government.

For these reasons, we are closing this pull request. If you have further questions, please feel free to contact [GitHub Support](https://support.github.com/contact).

**Pull request closed without merging**
