### PR TITLE
Sad news to hear on Github

### PR DESCRIPTION
**Pull request by sometent**
Finally Spain shares an entry in https://github.com/github/gov-takedowns with China and Russia. The Spanish government is involved in a witch hunting that attempts to prosecute any person or group of persons that want to peacefully protest against the status quo. In order to give some foundation to what I'm saying, let me enumerate some sources that show some hints that something wrong is happening in Spain about freedom of speech and public assembly.

1. [Brussels backs exiled rapper's arguments against extradition](https://www.catalannews.com/politics/item/brussels-backs-exiled-rapper-s-arguments-against-extradition): the rap singer Valtonyc is currently exiled in Belgium to avoid jail in Spain for the lyrics of some of his songs. The Belgian justice already rejected the extradition request.

2. [UN rights experts criticise Spanish efforts to block Catalan vote](https://www.theguardian.com/world/2017/sep/28/un-rights-experts-criticise-spanish-efforts-to-block-catalan-vote): UN human rights experts have weighed in on the escalating row over Catalonia’s independence referendum, warning the Spanish authorities that their “worrying” efforts to halt Sunday’s poll appear to violate fundamental rights and risk stifling debate “at a critical moment for Spain’s democracy”.

3. [Spain: Excessive use of force by National Police and Civil Guard in Catalonia](https://www.amnesty.org/en/latest/news/2017/10/spain-excessive-use-of-force-by-national-police-and-civil-guard-in-catalonia/): the same police that wrote Github for the takedown was accused by Amnisty International for excessive use of force.

4. [SPAIN: Authorities must de-escalate tensions and guarantee the right to public assembly](https://www.amnesty.org/en/latest/news/2019/10/spain-authorities-must-deescalate-tensions-and-guarantee-the-right-to-public-assembly/): here, Amnisty International is warning Spain about guaranteeing the right to public assembly.

5. [European Comission warns Spain about prosecuting Tsunami Democratic](https://diario16.com/la-comision-europea-da-un-toque-de-atencion-a-espana-por-la-persecucion-de-tsunami-democratic/): the comission recently warned Spain to preserve speech expression after shutting down Tsunami Democratic's movement websites. 

Spain is a democracy, but it still preserves some behaviors more typical from the fascist regime that preceded. Spain is currently accusing of terrorism a movement that emphasizes its peaceful nature. Nobody died, no bomb was put, no gun was shot by any protester in Catalonia. Tsunami Democratic is just a platform for coordinating protests of people whose reasons are legit and always in a peaceful manner. Spain is using some incidents done by a minority (the worst action was just burning trash containers) for accusing the entire movement of terrorism.

### CODE REVIEW

**Comment by tunnckoCore** [comment]
I agree. But I don't get why you are changing the text entirely. I thought this repository is for holding official requests directed to GitHub from officials.

**Comment by drpicox** [comment]
What is doing GitHub is great!
It is really nice to see a company doing real transparency.

But I do not understand your comment @tunnckoCore , ¿did you have read the README?

https://github.com/github/gov-takedowns#contributing

> **Contributing**
> We do not accept Pull Requests in this repository. _Feel free to comment or make suggestions_, 
> but note that we do not actively monitor contributions to this repository. 
> If you would like to contact GitHub about this repository, please contact GitHub Support.

GitHub is just embracing free of speech. That is wonderful!

**Comment by tunnckoCore** [comment]
> ¿did you have read the README?

Yes, I did. And as you quoted. It's nonsense to contribute such "changes". Such PRs are obviously out of scope.

**Comment by ratatoeey** [comment]
> Such PRs are obviously out of scope.

maybe people need a place to talk about it where visibility is high. though it would be nice if issues were enabled, then they could have been moved to a separate repo, one that links back to this repo.

is there a better place for this discussion?

----

https://github.com/github/gov-takedowns/pull/9 is also about this same takedown.

**Comment by tunnckoCore** [comment]
I don't see any sense and point in discussing something that is fact and you can't anyway do anything, or if so - GitHub is definitely not the place for that, especially by people that has nothing to do in GitHub in the first place. It's not a platform for discussions and thoughsands of nonsense accounts created for just few comments. There are tons of forums and Reddit for this. No need to register a GitHub account to share their opinions. That's complete nonsense and waste of time, and resources.

I assume issues are disabled exactly for that reason. I don't see what discussions have to with transparancy. This repository is to inform how Gov's and other forces are treating the world.

I don't have anything against those people, I'm in support of this groups and activists. The thing is that it doesn't make sense here.

> make suggestions

probably means, typos and such, not whole text replacements.

> free to comment

can be done as commit comment, without PRs. And yes, probably people may not be familiar with github and so don't know that feature, that's the reason they are opening PRs. But this leads us to what I'm talking above - it's not the right place in the first place.

**Comment by vollmera** [comment]
As we had stated the [previous version](https://github.com/github/gov-takedowns/tree/1eadc7c478b22addb8c7969eda9e49c5090faa77#contributing) of the README in this repo
>We do not accept Pull Requests in this repository.

To clarify and explain why, we made some [clarifications](https://github.com/github/gov-takedowns/blob/master/README.md), including
>We publicly post those notices, unchanged (other than redactions of personal information), because we are concerned about Internet censorship

and that
>We do not accept Pull Requests in this repository because the notices we post are verbatim from the notifying government.

For these reasons, we are closing this pull request. If you have further questions, please feel free to contact [GitHub Support](https://support.github.com/contact).

**Pull request closed without merging**
